# Use the same dynamic input loading as the VM deployment
filebeat.config.inputs:
  enabled: true
  path: /usr/local/sof-elk/lib/filebeat_inputs/*.yml

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~